### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by kuzniachka** [kuzniachka/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by anita-kznk** [comment]
**LIFE & EDUCATION**
To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.

**LANGUAGES**
🇺🇸 ENGLISH 🇨🇳 MANDARIN 🇯🇵 JAPANESE

**SKILLS**
KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

**CHARACTER**
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

**LIFE LESSON**
You must defeat Sheng Long to stand a chance.

**LIKES 😃**
GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

**DISLIKES 😞**
BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

**WANTS 🥺**
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by anita-kznk** [comment]
<section>
    <h3>Life & Education</h3>
    <p class="tags small">To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.</p>
</section>
<section>
    <h3>Languages</h3>
    <p class="tags small">
        <span class="language" lang="en">🇺🇸 ENGLISH</span>
        <span class="language" lang="zh">🇨🇳 MANDARIN</span>
        <span class="language" lang="ja">🇯🇵 JAPANESE</span>
    </p>
</section>
<section>
    <h3>Skills</h3>
    <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
</section>
<section>
    <h3>Character</h3>
    <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
</section>
<section>
    <h3>Life lessom</h3>
    <p class="tags small">You must defeat Sheng Long to stand a chance.</p>
</section>
<section>
    <h3>Likes 😃</h3>
    <p class="tags small">GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
</section>
<section>
    <h3>Dislikes 😞</h3>
    <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
</section>
<section>
    <h3>Wants 🥺</h3>
    <p class="tags small">BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
</section>
