### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by kuzniachka** [kuzniachka/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by kuzniachka** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by anita-kznk** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by anita-kznk** [comment]
<h2>Résumé</h2>
<p>&mdash; I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven. </p>

**Comment by anita-kznk** [comment]
@kuzniachka з'явились оновлені дані щодо аватару! Пропоную додати його в наш проект! Буде виглядати чудово! Використай сніпет із наступного коментаря!

**Comment by anita-kznk** [comment]
Ти знаєш, що зробити, аби з'явилась магія ->
<div class="avatar-wrapper">
                  <object class="avatar" style="height:150px;border-radius:75px;transform:scale(-1,1);" data="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/54c8c902-e578-478f-845b-25c5c2fd8d3f/d7jzmhs-1c9dba06-b22c-4aab-9e5a-7319b5d4d0b1.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNTRjOGM5MDItZTU3OC00NzhmLTg0NWItMjVjNWMyZmQ4ZDNmXC9kN2p6bWhzLTFjOWRiYTA2LWIyMmMtNGFhYi05ZTVhLTczMTliNWQ0ZDBiMS5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.uV4PS1mYLoOHceDCQpZyx-gZ3XCwg0vI1BxTJSDKBMo" role="img" aria-label="My profile picture"></object>
        </div>

**Comment by kuzniachka** [comment]
Дякую, @anita-kznk - що б я без тебе робила?!
